# Internal profile runtime builder for the Home Manager module.
#
# NOT exported from the flake's `lib`: `modules/home-manager.nix` is its only
# consumer. It turns one declared profile (npm-name -> pnpm-spec dependencies,
# a bundle list, an optional pnpm-workspace.yaml override, and the fixed-output
# dependency-closure hash) into a store derivation whose layout mirrors DSH's
# native profile geometry:
#
#   $out/profiles/
#   ├── node_modules/            # DSH host fallback (generated by DSH itself)
#   └── <name>/
#       ├── package.json
#       ├── pnpm-workspace.yaml
#       └── node_modules/        # pnpm-constructed runtime graph (only with dependencies)
#
# The pipeline is fixed:
#   1. `profileSource` calls the current DSH package's own
#      `dsh plugin --profile <name> --version`, which runs DSH's `initProfile()`
#      and yields the canonical package.json / pnpm-workspace.yaml /
#      cordis.patch.yml (so future DSH profile-policy changes flow through the
#      new `finalPackage` automatically). The manifest is kept at
#      `dependencies = {}` while the DSH-paired pnpm writes a placeholder
#      `pnpm-lock.yaml` (`--lockfile-only --offline`), then the manifest is
#      overwritten with the real dependencies + bundles.
#   2. When dependencies exist, `fetchPnpmDeps` (fetcherVersion 4, the DSH-paired
#      pnpm) resolves the real lockfile through `prePnpmInstall` and fetches the
#      fixed pnpm store; its `postInstall` copies the resolved lockfile out.
#   3. The runtime derivation swaps the resolved lockfile in, runs Nixpkgs'
#      `pnpmConfigHook` (offline frozen install, `--ignore-scripts`), then a
#      second offline frozen install without `--ignore-scripts` so `allowBuilds`
#      lifecycle scripts run inside the Nix sandbox.
#   4. `DSH_HOME=$out dsh --profile <name> --dump-default-config` makes DSH
#      itself build the `profiles/node_modules` host fallback and validates the
#      manifest, bundle resolution, and bundle patch composition; the temporary
#      `cordis.yml` DSH writes is removed (that file stays runtime-owned).
#
# `cordisPatch` deliberately is not an input: editing a profile's patch layer
# must not rebuild its dependency graph.
{
  lib,
  pkgs,
}:

let
  yamlLib = import ./yaml.nix { inherit lib pkgs; };

  empty = attrs: lib.attrNames attrs == [ ];
in
{
  mkProfileRuntime =
    {
      dshPackage,
      name,
      dependencies,
      bundles,
      pnpmWorkspace,
      pnpmDepsHash,
    }:
    let
      hasDependencies = !empty dependencies;

      # 1. Canonical profile source: DSH's own initProfile output, a workspace
      # override when one is configured, the placeholder lockfile from the
      # DSH-paired pnpm, and the real manifest.
      profileSource =
        let
          workspaceYaml =
            if pnpmWorkspace == null then null else yamlLib.generate "pnpm-workspace.yaml" pnpmWorkspace;
          manifestJson = builtins.toJSON {
            name = "dsh-profile-${name}";
            private = true;
            dependencies = dependencies;
            dsh = {
              profile = {
                bundles = bundles;
              };
            };
          };
        in
        pkgs.stdenv.mkDerivation {
          pname = "dsh-profile-${name}-source";
          version = "0";
          nativeBuildInputs = [
            dshPackage.passthru.nodejs
            dshPackage.passthru.pnpm
          ];
          inherit workspaceYaml manifestJson;
          buildCommand = ''
              export HOME="$TMPDIR"
              export DSH_HOME="$TMPDIR/dsh-home"
              export DSH_TELEMETRY_DISABLED=1

              # DSH initializes the profile: canonical package.json (dependencies
              # = {}), pnpm-workspace.yaml, and cordis.patch.yml template.
              "${dshPackage}/bin/dsh" plugin --profile ${lib.escapeShellArg name} --version >/dev/null
              profileDir="$DSH_HOME/profiles/${lib.escapeShellArg name}"

              ${lib.optionalString (pnpmWorkspace != null) ''
                cp "$workspaceYaml" "$profileDir/pnpm-workspace.yaml"
              ''}

              # Placeholder lockfile for an empty dependency set, written by the
              # same pnpm the DSH runtime pairs with.
              (cd "$profileDir" && pnpm install --lockfile-only --offline --ignore-scripts)

              # Overwrite with the real manifest (dependencies + bundles).
              cat > "$profileDir/package.json" <<'JSON'
            ${manifestJson}
            JSON

              mkdir -p "$out"
              cp "$profileDir/package.json" "$out/package.json"
              cp "$profileDir/pnpm-workspace.yaml" "$out/pnpm-workspace.yaml"
              cp "$profileDir/pnpm-lock.yaml" "$out/pnpm-lock.yaml"
          '';
        };

      # 2. The fixed-output dependency closure. `prePnpmInstall` lets the
      # resolver regenerate the real lockfile from the manifest (network is
      # available to fixed-output derivations); the built-in frozen install
      # then fetches the complete pnpm store; `postInstall` keeps the resolved
      # lockfile next to the store for the runtime derivation.
      resolvedDeps = pkgs.fetchPnpmDeps {
        inherit (dshPackage.passthru) pnpm;
        pname = "dsh-profile-${name}-deps";
        src = profileSource;
        hash = if pnpmDepsHash == null then lib.fakeHash else pnpmDepsHash;
        fetcherVersion = 4;
        prePnpmInstall = ''
          pnpm install \
            --lockfile-only \
            --ignore-scripts \
            --no-frozen-lockfile \
            --registry="$NIX_NPM_REGISTRY"
        '';
        postInstall = ''
          cp pnpm-lock.yaml "$out/pnpm-lock.yaml"
        '';
      };

      # 3. The sandboxed profile runtime. The real lockfile replaces the
      # placeholder before pnpmConfigHook's frozen install; the second install
      # reuses the same fixed store and runs allowed lifecycle scripts.
      profileRuntime = pkgs.stdenv.mkDerivation {
        pname = "dsh-profile-${name}-runtime";
        version = "0";
        src = profileSource;
        pnpmDeps = resolvedDeps;
        nativeBuildInputs = [
          dshPackage.passthru.nodejs
          dshPackage.passthru.pnpm
          pkgs.pnpmConfigHook
        ];
        prePnpmInstall = ''
          cp "${resolvedDeps}/pnpm-lock.yaml" pnpm-lock.yaml
        '';
        buildPhase = ''
          runHook preBuild
          # pnpmConfigHook installs with --ignore-scripts; a fresh offline
          # frozen install is what runs `allowBuilds` lifecycle scripts.
          rm -rf node_modules
          pnpm install --offline --frozen-lockfile
          runHook postBuild
        '';
        installPhase = ''
          runHook preInstall
          # pnpm's bookkeeping records the sandbox store path; nothing reads
          # it at runtime (pnpm never runs against a Home Manager-managed
          # profile), so drop it to keep the output self-contained.
          rm -f node_modules/.modules.yaml node_modules/.pnpm-workspace-state-v1.json
          mkdir -p "$out/profiles/${lib.escapeShellArg name}"
          cp package.json pnpm-workspace.yaml "$out/profiles/${lib.escapeShellArg name}/"
          cp -a node_modules "$out/profiles/${lib.escapeShellArg name}/"
          runHook postInstall
        '';
        postInstall = ''
          export HOME="$TMPDIR"
          export DSH_HOME="$out"
          export DSH_TELEMETRY_DISABLED=1

          # DSH itself heals `profiles/node_modules` (the host fallback) and
          # validates the manifest, bundle resolution, and bundle patch
          # composition against this exact runtime.
          "${dshPackage}/bin/dsh" --profile ${lib.escapeShellArg name} --dump-default-config >/dev/null

          # DSH rewrites the profile root config on every boot; it stays a
          # runtime-owned file in the user's home, not a store artifact.
          rm -f "$out/profiles/${lib.escapeShellArg name}/cordis.yml"
        '';
      };
    in
    if hasDependencies then
      profileRuntime
    else
      # An installation-owned-only profile has no dependency graph: no
      # fetchPnpmDeps, no pnpmDepsHash, no profile-local node_modules. DSH
      # heals the host fallback at first boot.
      pkgs.runCommand "dsh-profile-${name}" { } ''
        mkdir -p "$out/profiles/${lib.escapeShellArg name}"
        cp "${profileSource}/package.json" "${profileSource}/pnpm-workspace.yaml" "$out/profiles/${lib.escapeShellArg name}/"
      '';
}
